# config.yml

# A list of email recipients to be notified
email_recipients:
  - ethankethank@gmail.com
  - eckenned@umich.edu

# Acceptable duration (in minutes) to not receive a response from the remote system
remote_response_threshold: 15

# Set points for different water quality parameters
parameters:
  pH:
    min: 6.5
    max: 7.5
  Temp:
    min: 20
    max: 30
  NH4:
    min: 0
    max: 50
  Nitrate:
    min: 0
    max: 100
  Dissolved_Oxygen:
    min: 5
    max: 12
  ORP:
    min: 200
    max: 400

# The specific time of day to receive a running message (in 24-hour format) NOTE: This is in UTC time
message_schedule: "15:02"
